spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:used_car_db
    username: dbuser
    password: dbpassword
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: 02e05d259ad1b09149f0f47814b076a82a7f62bcad83372ba36c45caff1eb227
  expiration-time-millis: 620_000
